import Head from "next/head";
import styles from "../styles/Global.module.css";
import Header from "../component/header";
import React, { useState } from "react";

export default function Route() {
  const [route, setRoute] = useState("");
  const dynamicRoutes = ["filters", "buy"];
  const generateRoute = () => {
    let result = "";
    const characters =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    for (var i = 0; i < 10; i++) {
      result += characters.charAt(
        Math.floor(Math.random() * characters.length)
      );
    }
    const random = Math.floor(Math.random() * dynamicRoutes.length);
    setRoute(`/${dynamicRoutes[random]}/${result}`);

    const nextTitle = "Dynamic Routing App";
    const nextState = { additionalInformation: "Updated the URL with JS" };
    window.history.pushState(
      nextState,
      nextTitle,
      `/${dynamicRoutes[random]}/${result}`
    );
    window.history.replaceState(
      nextState,
      nextTitle,
      `/${dynamicRoutes[random]}/${result}`
    );
  };
  return (
    <>
      <Head>
        <title>Dynamic Routing App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1>Route Page</h1>
        <p>Route Value : {`${route}`}</p>
        <button onClick={() => generateRoute()}>Change Route</button>
      </main>
    </>
  );
}
